### ISSUE TITLE
No updates in 21 days

### ISSUE THREAD

**Issue by madrus** [lydiahallie/graphql-workshop#1]
Hi Lydia, are you still planning to add solutions to your workshop tasks?
Sorry for this way of asking but I am sure that many of your listeners from Amsterdam would really appreciate of you do that please.
Best regards,
Andre

**Comment by lydiahallie** [comment]
Sorry about the delay. Expect updates in the first week of September 😄

**Comment by madrus** [comment]
Hi Lydia,

Please be so kind!

André

**Comment by lydiahallie** [comment]
Pushed https://github.com/lydiahallie/graphql-workshop/tree/solutions 👍 Sorry for the delay

**Comment by madrus** [comment]
Hi Lydia,
That is great news. Thank you very much! And it is super handy you have
placed the solutions in a separate branch.
Great job!
Best regards,
André
